//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class livros
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string ediçao { get; set; }
        public Nullable<int> ano { get; set; }
    }
}
